name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
      - name: Run Maven Tests
        run: mvn clean install

  release:
    name: Semantic Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release to analyze all commits
      - name: Set up Java
        uses: actions/setup-java@v4
      - name: Set up Semantic Release
        run: |
          npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          
  deploy:
    name: Deploy to GitHub Packages
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Deploy to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}